#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRNSoft
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GRN")]
	public partial class UniGRNDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGRNDetail(GRNDetail instance);
    partial void UpdateGRNDetail(GRNDetail instance);
    partial void DeleteGRNDetail(GRNDetail instance);
    partial void InsertGRNItemDetail(GRNItemDetail instance);
    partial void UpdateGRNItemDetail(GRNItemDetail instance);
    partial void DeleteGRNItemDetail(GRNItemDetail instance);
    #endregion
		
		public UniGRNDbDataContext() : 
				base(global::GRNSoft.Properties.Settings.Default.GRNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UniGRNDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniGRNDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniGRNDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniGRNDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GRNDetail> GRNDetails
		{
			get
			{
				return this.GetTable<GRNDetail>();
			}
		}
		
		public System.Data.Linq.Table<GRNItemDetail> GRNItemDetails
		{
			get
			{
				return this.GetTable<GRNItemDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GRNDetail")]
	public partial class GRNDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GRNNo;
		
		private System.DateTime _GRNDate;
		
		private string _Supplier;
		
		private string _ChallanNo;
		
		private System.Nullable<System.DateTime> _ChallanDate;
		
		private string _PONo;
		
		private System.Nullable<System.DateTime> _PODate;
		
		private string _VehicalNo;
		
		private string _OctroiReceiptNo;
		
		private string _ReasonForRejection;
		
		private EntitySet<GRNItemDetail> _GRNItemDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRNNoChanging(int value);
    partial void OnGRNNoChanged();
    partial void OnGRNDateChanging(System.DateTime value);
    partial void OnGRNDateChanged();
    partial void OnSupplierChanging(string value);
    partial void OnSupplierChanged();
    partial void OnChallanNoChanging(string value);
    partial void OnChallanNoChanged();
    partial void OnChallanDateChanging(System.Nullable<System.DateTime> value);
    partial void OnChallanDateChanged();
    partial void OnPONoChanging(string value);
    partial void OnPONoChanged();
    partial void OnPODateChanging(System.Nullable<System.DateTime> value);
    partial void OnPODateChanged();
    partial void OnVehicalNoChanging(string value);
    partial void OnVehicalNoChanged();
    partial void OnOctroiReceiptNoChanging(string value);
    partial void OnOctroiReceiptNoChanged();
    partial void OnReasonForRejectionChanging(string value);
    partial void OnReasonForRejectionChanged();
    #endregion
		
		public GRNDetail()
		{
			this._GRNItemDetails = new EntitySet<GRNItemDetail>(new Action<GRNItemDetail>(this.attach_GRNItemDetails), new Action<GRNItemDetail>(this.detach_GRNItemDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int GRNNo
		{
			get
			{
				return this._GRNNo;
			}
			set
			{
				if ((this._GRNNo != value))
				{
					this.OnGRNNoChanging(value);
					this.SendPropertyChanging();
					this._GRNNo = value;
					this.SendPropertyChanged("GRNNo");
					this.OnGRNNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNDate", DbType="Date NOT NULL")]
		public System.DateTime GRNDate
		{
			get
			{
				return this._GRNDate;
			}
			set
			{
				if ((this._GRNDate != value))
				{
					this.OnGRNDateChanging(value);
					this.SendPropertyChanging();
					this._GRNDate = value;
					this.SendPropertyChanged("GRNDate");
					this.OnGRNDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Supplier
		{
			get
			{
				return this._Supplier;
			}
			set
			{
				if ((this._Supplier != value))
				{
					this.OnSupplierChanging(value);
					this.SendPropertyChanging();
					this._Supplier = value;
					this.SendPropertyChanged("Supplier");
					this.OnSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanNo", DbType="NVarChar(50)")]
		public string ChallanNo
		{
			get
			{
				return this._ChallanNo;
			}
			set
			{
				if ((this._ChallanNo != value))
				{
					this.OnChallanNoChanging(value);
					this.SendPropertyChanging();
					this._ChallanNo = value;
					this.SendPropertyChanged("ChallanNo");
					this.OnChallanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanDate", DbType="Date")]
		public System.Nullable<System.DateTime> ChallanDate
		{
			get
			{
				return this._ChallanDate;
			}
			set
			{
				if ((this._ChallanDate != value))
				{
					this.OnChallanDateChanging(value);
					this.SendPropertyChanging();
					this._ChallanDate = value;
					this.SendPropertyChanged("ChallanDate");
					this.OnChallanDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONo", DbType="NVarChar(50)")]
		public string PONo
		{
			get
			{
				return this._PONo;
			}
			set
			{
				if ((this._PONo != value))
				{
					this.OnPONoChanging(value);
					this.SendPropertyChanging();
					this._PONo = value;
					this.SendPropertyChanged("PONo");
					this.OnPONoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PODate", DbType="Date")]
		public System.Nullable<System.DateTime> PODate
		{
			get
			{
				return this._PODate;
			}
			set
			{
				if ((this._PODate != value))
				{
					this.OnPODateChanging(value);
					this.SendPropertyChanging();
					this._PODate = value;
					this.SendPropertyChanged("PODate");
					this.OnPODateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicalNo", DbType="NVarChar(50)")]
		public string VehicalNo
		{
			get
			{
				return this._VehicalNo;
			}
			set
			{
				if ((this._VehicalNo != value))
				{
					this.OnVehicalNoChanging(value);
					this.SendPropertyChanging();
					this._VehicalNo = value;
					this.SendPropertyChanged("VehicalNo");
					this.OnVehicalNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OctroiReceiptNo", DbType="NVarChar(50)")]
		public string OctroiReceiptNo
		{
			get
			{
				return this._OctroiReceiptNo;
			}
			set
			{
				if ((this._OctroiReceiptNo != value))
				{
					this.OnOctroiReceiptNoChanging(value);
					this.SendPropertyChanging();
					this._OctroiReceiptNo = value;
					this.SendPropertyChanged("OctroiReceiptNo");
					this.OnOctroiReceiptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonForRejection", DbType="NVarChar(MAX)")]
		public string ReasonForRejection
		{
			get
			{
				return this._ReasonForRejection;
			}
			set
			{
				if ((this._ReasonForRejection != value))
				{
					this.OnReasonForRejectionChanging(value);
					this.SendPropertyChanging();
					this._ReasonForRejection = value;
					this.SendPropertyChanged("ReasonForRejection");
					this.OnReasonForRejectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GRNDetail_GRNItemDetail", Storage="_GRNItemDetails", ThisKey="GRNNo", OtherKey="GRNNo")]
		public EntitySet<GRNItemDetail> GRNItemDetails
		{
			get
			{
				return this._GRNItemDetails;
			}
			set
			{
				this._GRNItemDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GRNItemDetails(GRNItemDetail entity)
		{
			this.SendPropertyChanging();
			entity.GRNDetail = this;
		}
		
		private void detach_GRNItemDetails(GRNItemDetail entity)
		{
			this.SendPropertyChanging();
			entity.GRNDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GRNItemDetail")]
	public partial class GRNItemDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GRNItemID;
		
		private string _ItemCode;
		
		private string _Description;
		
		private int _Challan;
		
		private string _ChallanUnit;
		
		private decimal _Actual;
		
		private string _ActualUnit;
		
		private string _Accepted;
		
		private string _Remarks;
		
		private int _GRNNo;
		
		private EntityRef<GRNDetail> _GRNDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRNItemIDChanging(int value);
    partial void OnGRNItemIDChanged();
    partial void OnItemCodeChanging(string value);
    partial void OnItemCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnChallanChanging(int value);
    partial void OnChallanChanged();
    partial void OnChallanUnitChanging(string value);
    partial void OnChallanUnitChanged();
    partial void OnActualChanging(decimal value);
    partial void OnActualChanged();
    partial void OnActualUnitChanging(string value);
    partial void OnActualUnitChanged();
    partial void OnAcceptedChanging(string value);
    partial void OnAcceptedChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnGRNNoChanging(int value);
    partial void OnGRNNoChanged();
    #endregion
		
		public GRNItemDetail()
		{
			this._GRNDetail = default(EntityRef<GRNDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNItemID", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GRNItemID
		{
			get
			{
				return this._GRNItemID;
			}
			set
			{
				if ((this._GRNItemID != value))
				{
					this.OnGRNItemIDChanging(value);
					this.SendPropertyChanging();
					this._GRNItemID = value;
					this.SendPropertyChanged("GRNItemID");
					this.OnGRNItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this.OnItemCodeChanging(value);
					this.SendPropertyChanging();
					this._ItemCode = value;
					this.SendPropertyChanged("ItemCode");
					this.OnItemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Challan", DbType="Int NOT NULL")]
		public int Challan
		{
			get
			{
				return this._Challan;
			}
			set
			{
				if ((this._Challan != value))
				{
					this.OnChallanChanging(value);
					this.SendPropertyChanging();
					this._Challan = value;
					this.SendPropertyChanged("Challan");
					this.OnChallanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanUnit", DbType="NVarChar(50)")]
		public string ChallanUnit
		{
			get
			{
				return this._ChallanUnit;
			}
			set
			{
				if ((this._ChallanUnit != value))
				{
					this.OnChallanUnitChanging(value);
					this.SendPropertyChanging();
					this._ChallanUnit = value;
					this.SendPropertyChanged("ChallanUnit");
					this.OnChallanUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actual", DbType="Decimal(18,3) NOT NULL")]
		public decimal Actual
		{
			get
			{
				return this._Actual;
			}
			set
			{
				if ((this._Actual != value))
				{
					this.OnActualChanging(value);
					this.SendPropertyChanging();
					this._Actual = value;
					this.SendPropertyChanged("Actual");
					this.OnActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualUnit", DbType="NVarChar(50)")]
		public string ActualUnit
		{
			get
			{
				return this._ActualUnit;
			}
			set
			{
				if ((this._ActualUnit != value))
				{
					this.OnActualUnitChanging(value);
					this.SendPropertyChanging();
					this._ActualUnit = value;
					this.SendPropertyChanged("ActualUnit");
					this.OnActualUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accepted", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Accepted
		{
			get
			{
				return this._Accepted;
			}
			set
			{
				if ((this._Accepted != value))
				{
					this.OnAcceptedChanging(value);
					this.SendPropertyChanging();
					this._Accepted = value;
					this.SendPropertyChanged("Accepted");
					this.OnAcceptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNNo", DbType="Int NOT NULL")]
		public int GRNNo
		{
			get
			{
				return this._GRNNo;
			}
			set
			{
				if ((this._GRNNo != value))
				{
					if (this._GRNDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGRNNoChanging(value);
					this.SendPropertyChanging();
					this._GRNNo = value;
					this.SendPropertyChanged("GRNNo");
					this.OnGRNNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GRNDetail_GRNItemDetail", Storage="_GRNDetail", ThisKey="GRNNo", OtherKey="GRNNo", IsForeignKey=true)]
		public GRNDetail GRNDetail
		{
			get
			{
				return this._GRNDetail.Entity;
			}
			set
			{
				GRNDetail previousValue = this._GRNDetail.Entity;
				if (((previousValue != value) 
							|| (this._GRNDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GRNDetail.Entity = null;
						previousValue.GRNItemDetails.Remove(this);
					}
					this._GRNDetail.Entity = value;
					if ((value != null))
					{
						value.GRNItemDetails.Add(this);
						this._GRNNo = value.GRNNo;
					}
					else
					{
						this._GRNNo = default(int);
					}
					this.SendPropertyChanged("GRNDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
