#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIRecruitmentSoft
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNIRecruitment")]
	public partial class UniDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKeyValueDetail(KeyValueDetail instance);
    partial void UpdateKeyValueDetail(KeyValueDetail instance);
    partial void DeleteKeyValueDetail(KeyValueDetail instance);
    partial void InsertUserDetail(UserDetail instance);
    partial void UpdateUserDetail(UserDetail instance);
    partial void DeleteUserDetail(UserDetail instance);
    partial void InsertCandidateDetail(CandidateDetail instance);
    partial void UpdateCandidateDetail(CandidateDetail instance);
    partial void DeleteCandidateDetail(CandidateDetail instance);
    partial void InsertVendorDetail(VendorDetail instance);
    partial void UpdateVendorDetail(VendorDetail instance);
    partial void DeleteVendorDetail(VendorDetail instance);
    partial void InsertCustomerDetail(CustomerDetail instance);
    partial void UpdateCustomerDetail(CustomerDetail instance);
    partial void DeleteCustomerDetail(CustomerDetail instance);
    partial void InsertSMSHistory(SMSHistory instance);
    partial void UpdateSMSHistory(SMSHistory instance);
    partial void DeleteSMSHistory(SMSHistory instance);
    partial void InsertVisitDetail(VisitDetail instance);
    partial void UpdateVisitDetail(VisitDetail instance);
    partial void DeleteVisitDetail(VisitDetail instance);
    partial void InsertEmailHistory(EmailHistory instance);
    partial void UpdateEmailHistory(EmailHistory instance);
    partial void DeleteEmailHistory(EmailHistory instance);
    #endregion
		
		public UniDBDataContext() : 
				base(global::UNIRecruitmentSoft.Properties.Settings.Default.UNIRecruitmentConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UniDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KeyValueDetail> KeyValueDetails
		{
			get
			{
				return this.GetTable<KeyValueDetail>();
			}
		}
		
		public System.Data.Linq.Table<UserDetail> UserDetails
		{
			get
			{
				return this.GetTable<UserDetail>();
			}
		}
		
		public System.Data.Linq.Table<CandidateDetail> CandidateDetails
		{
			get
			{
				return this.GetTable<CandidateDetail>();
			}
		}
		
		public System.Data.Linq.Table<VendorDetail> VendorDetails
		{
			get
			{
				return this.GetTable<VendorDetail>();
			}
		}
		
		public System.Data.Linq.Table<CustomerDetail> CustomerDetails
		{
			get
			{
				return this.GetTable<CustomerDetail>();
			}
		}
		
		public System.Data.Linq.Table<SMSHistory> SMSHistories
		{
			get
			{
				return this.GetTable<SMSHistory>();
			}
		}
		
		public System.Data.Linq.Table<VisitDetail> VisitDetails
		{
			get
			{
				return this.GetTable<VisitDetail>();
			}
		}
		
		public System.Data.Linq.Table<EmailHistory> EmailHistories
		{
			get
			{
				return this.GetTable<EmailHistory>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReCalculateAge")]
		public int ReCalculateAge()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreateBackUp")]
		public int CreateBackUp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KeyValueDetail")]
	public partial class KeyValueDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KayName;
		
		private string _ValueName;
		
		private string _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKayNameChanging(string value);
    partial void OnKayNameChanged();
    partial void OnValueNameChanging(string value);
    partial void OnValueNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public KeyValueDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KayName
		{
			get
			{
				return this._KayName;
			}
			set
			{
				if ((this._KayName != value))
				{
					this.OnKayNameChanging(value);
					this.SendPropertyChanging();
					this._KayName = value;
					this.SendPropertyChanged("KayName");
					this.OnKayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueName", DbType="NVarChar(50)")]
		public string ValueName
		{
			get
			{
				return this._ValueName;
			}
			set
			{
				if ((this._ValueName != value))
				{
					this.OnValueNameChanging(value);
					this.SendPropertyChanging();
					this._ValueName = value;
					this.SendPropertyChanged("ValueName");
					this.OnValueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserDetail")]
	public partial class UserDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ExecutiveName;
		
		private string _MobileNo;
		
		private string _EmailId;
		
		private string _UserId;
		
		private string _Password;
		
		private string _Modules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnModulesChanging(string value);
    partial void OnModulesChanged();
    #endregion
		
		public UserDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(50)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this.OnEmailIdChanging(value);
					this.SendPropertyChanging();
					this._EmailId = value;
					this.SendPropertyChanged("EmailId");
					this.OnEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modules", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Modules
		{
			get
			{
				return this._Modules;
			}
			set
			{
				if ((this._Modules != value))
				{
					this.OnModulesChanging(value);
					this.SendPropertyChanging();
					this._Modules = value;
					this.SendPropertyChanged("Modules");
					this.OnModulesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateDetail")]
	public partial class CandidateDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private string _Link;
		
		private System.DateTime _ProcessedDate;
		
		private string _Name;
		
		private System.Nullable<long> _CandidateCode;
		
		private string _Gender;
		
		private System.DateTime _DateOfBirth;
		
		private int _Age;
		
		private string _CurrentLocation;
		
		private string _PreferedLocation;
		
		private string _MobileNo;
		
		private string _LandLineNo;
		
		private string _Email;
		
		private string _Qualification;
		
		private string _AdditionalQualification;
		
		private int _Experience;
		
		private string _ExpSlap;
		
		private string _JobTitle;
		
		private string _CurrentIndustry;
		
		private string _PreferredIndustry;
		
		private string _NoticePeriod;
		
		private string _CurrentCTC;
		
		private string _ExpectedCTC;
		
		private int _NoOfCalls;
		
		private string _Remarks;
		
		private string _CVPath;
		
		private bool _Registered;
		
		private bool _Placed;
		
		private string _MarritalStatus;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private string _CallLetter1;
		
		private string _CallLetter2;
		
		private string _CallLetter3;
		
		private string _CallLetter4;
		
		private string _CallLetter5;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnProcessedDateChanging(System.DateTime value);
    partial void OnProcessedDateChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCandidateCodeChanging(System.Nullable<long> value);
    partial void OnCandidateCodeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDateOfBirthChanging(System.DateTime value);
    partial void OnDateOfBirthChanged();
    partial void OnAgeChanging(int value);
    partial void OnAgeChanged();
    partial void OnCurrentLocationChanging(string value);
    partial void OnCurrentLocationChanged();
    partial void OnPreferedLocationChanging(string value);
    partial void OnPreferedLocationChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnLandLineNoChanging(string value);
    partial void OnLandLineNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQualificationChanging(string value);
    partial void OnQualificationChanged();
    partial void OnAdditionalQualificationChanging(string value);
    partial void OnAdditionalQualificationChanged();
    partial void OnExperienceChanging(int value);
    partial void OnExperienceChanged();
    partial void OnExpSlapChanging(string value);
    partial void OnExpSlapChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnCurrentIndustryChanging(string value);
    partial void OnCurrentIndustryChanged();
    partial void OnPreferredIndustryChanging(string value);
    partial void OnPreferredIndustryChanged();
    partial void OnNoticePeriodChanging(string value);
    partial void OnNoticePeriodChanged();
    partial void OnCurrentCTCChanging(string value);
    partial void OnCurrentCTCChanged();
    partial void OnExpectedCTCChanging(string value);
    partial void OnExpectedCTCChanged();
    partial void OnNoOfCallsChanging(int value);
    partial void OnNoOfCallsChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnCVPathChanging(string value);
    partial void OnCVPathChanged();
    partial void OnRegisteredChanging(bool value);
    partial void OnRegisteredChanged();
    partial void OnPlacedChanging(bool value);
    partial void OnPlacedChanged();
    partial void OnMarritalStatusChanging(string value);
    partial void OnMarritalStatusChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnCallLetter1Changing(string value);
    partial void OnCallLetter1Changed();
    partial void OnCallLetter2Changing(string value);
    partial void OnCallLetter2Changed();
    partial void OnCallLetter3Changing(string value);
    partial void OnCallLetter3Changed();
    partial void OnCallLetter4Changing(string value);
    partial void OnCallLetter4Changed();
    partial void OnCallLetter5Changing(string value);
    partial void OnCallLetter5Changed();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public CandidateDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(50)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedDate", DbType="Date NOT NULL")]
		public System.DateTime ProcessedDate
		{
			get
			{
				return this._ProcessedDate;
			}
			set
			{
				if ((this._ProcessedDate != value))
				{
					this.OnProcessedDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessedDate = value;
					this.SendPropertyChanged("ProcessedDate");
					this.OnProcessedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateCode", DbType="BigInt")]
		public System.Nullable<long> CandidateCode
		{
			get
			{
				return this._CandidateCode;
			}
			set
			{
				if ((this._CandidateCode != value))
				{
					this.OnCandidateCodeChanging(value);
					this.SendPropertyChanging();
					this._CandidateCode = value;
					this.SendPropertyChanged("CandidateCode");
					this.OnCandidateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date NOT NULL")]
		public System.DateTime DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentLocation", DbType="NVarChar(100)")]
		public string CurrentLocation
		{
			get
			{
				return this._CurrentLocation;
			}
			set
			{
				if ((this._CurrentLocation != value))
				{
					this.OnCurrentLocationChanging(value);
					this.SendPropertyChanging();
					this._CurrentLocation = value;
					this.SendPropertyChanged("CurrentLocation");
					this.OnCurrentLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferedLocation", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PreferedLocation
		{
			get
			{
				return this._PreferedLocation;
			}
			set
			{
				if ((this._PreferedLocation != value))
				{
					this.OnPreferedLocationChanging(value);
					this.SendPropertyChanging();
					this._PreferedLocation = value;
					this.SendPropertyChanged("PreferedLocation");
					this.OnPreferedLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(11)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLineNo", DbType="NVarChar(12)")]
		public string LandLineNo
		{
			get
			{
				return this._LandLineNo;
			}
			set
			{
				if ((this._LandLineNo != value))
				{
					this.OnLandLineNoChanging(value);
					this.SendPropertyChanging();
					this._LandLineNo = value;
					this.SendPropertyChanged("LandLineNo");
					this.OnLandLineNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualification", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Qualification
		{
			get
			{
				return this._Qualification;
			}
			set
			{
				if ((this._Qualification != value))
				{
					this.OnQualificationChanging(value);
					this.SendPropertyChanging();
					this._Qualification = value;
					this.SendPropertyChanged("Qualification");
					this.OnQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalQualification", DbType="NVarChar(250)")]
		public string AdditionalQualification
		{
			get
			{
				return this._AdditionalQualification;
			}
			set
			{
				if ((this._AdditionalQualification != value))
				{
					this.OnAdditionalQualificationChanging(value);
					this.SendPropertyChanging();
					this._AdditionalQualification = value;
					this.SendPropertyChanged("AdditionalQualification");
					this.OnAdditionalQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="Int NOT NULL")]
		public int Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpSlap", DbType="NVarChar(50)")]
		public string ExpSlap
		{
			get
			{
				return this._ExpSlap;
			}
			set
			{
				if ((this._ExpSlap != value))
				{
					this.OnExpSlapChanging(value);
					this.SendPropertyChanging();
					this._ExpSlap = value;
					this.SendPropertyChanged("ExpSlap");
					this.OnExpSlapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentIndustry", DbType="NVarChar(250)")]
		public string CurrentIndustry
		{
			get
			{
				return this._CurrentIndustry;
			}
			set
			{
				if ((this._CurrentIndustry != value))
				{
					this.OnCurrentIndustryChanging(value);
					this.SendPropertyChanging();
					this._CurrentIndustry = value;
					this.SendPropertyChanged("CurrentIndustry");
					this.OnCurrentIndustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredIndustry", DbType="NVarChar(250)")]
		public string PreferredIndustry
		{
			get
			{
				return this._PreferredIndustry;
			}
			set
			{
				if ((this._PreferredIndustry != value))
				{
					this.OnPreferredIndustryChanging(value);
					this.SendPropertyChanging();
					this._PreferredIndustry = value;
					this.SendPropertyChanged("PreferredIndustry");
					this.OnPreferredIndustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticePeriod", DbType="NVarChar(50)")]
		public string NoticePeriod
		{
			get
			{
				return this._NoticePeriod;
			}
			set
			{
				if ((this._NoticePeriod != value))
				{
					this.OnNoticePeriodChanging(value);
					this.SendPropertyChanging();
					this._NoticePeriod = value;
					this.SendPropertyChanged("NoticePeriod");
					this.OnNoticePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentCTC", DbType="NVarChar(50)")]
		public string CurrentCTC
		{
			get
			{
				return this._CurrentCTC;
			}
			set
			{
				if ((this._CurrentCTC != value))
				{
					this.OnCurrentCTCChanging(value);
					this.SendPropertyChanging();
					this._CurrentCTC = value;
					this.SendPropertyChanged("CurrentCTC");
					this.OnCurrentCTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedCTC", DbType="NVarChar(250)")]
		public string ExpectedCTC
		{
			get
			{
				return this._ExpectedCTC;
			}
			set
			{
				if ((this._ExpectedCTC != value))
				{
					this.OnExpectedCTCChanging(value);
					this.SendPropertyChanging();
					this._ExpectedCTC = value;
					this.SendPropertyChanged("ExpectedCTC");
					this.OnExpectedCTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfCalls", DbType="Int NOT NULL")]
		public int NoOfCalls
		{
			get
			{
				return this._NoOfCalls;
			}
			set
			{
				if ((this._NoOfCalls != value))
				{
					this.OnNoOfCallsChanging(value);
					this.SendPropertyChanging();
					this._NoOfCalls = value;
					this.SendPropertyChanged("NoOfCalls");
					this.OnNoOfCallsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVPath", DbType="NVarChar(MAX)")]
		public string CVPath
		{
			get
			{
				return this._CVPath;
			}
			set
			{
				if ((this._CVPath != value))
				{
					this.OnCVPathChanging(value);
					this.SendPropertyChanging();
					this._CVPath = value;
					this.SendPropertyChanged("CVPath");
					this.OnCVPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registered", DbType="Bit NOT NULL")]
		public bool Registered
		{
			get
			{
				return this._Registered;
			}
			set
			{
				if ((this._Registered != value))
				{
					this.OnRegisteredChanging(value);
					this.SendPropertyChanging();
					this._Registered = value;
					this.SendPropertyChanged("Registered");
					this.OnRegisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placed", DbType="Bit NOT NULL")]
		public bool Placed
		{
			get
			{
				return this._Placed;
			}
			set
			{
				if ((this._Placed != value))
				{
					this.OnPlacedChanging(value);
					this.SendPropertyChanging();
					this._Placed = value;
					this.SendPropertyChanged("Placed");
					this.OnPlacedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarritalStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MarritalStatus
		{
			get
			{
				return this._MarritalStatus;
			}
			set
			{
				if ((this._MarritalStatus != value))
				{
					this.OnMarritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MarritalStatus = value;
					this.SendPropertyChanged("MarritalStatus");
					this.OnMarritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50)")]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallLetter1", DbType="NVarChar(MAX)")]
		public string CallLetter1
		{
			get
			{
				return this._CallLetter1;
			}
			set
			{
				if ((this._CallLetter1 != value))
				{
					this.OnCallLetter1Changing(value);
					this.SendPropertyChanging();
					this._CallLetter1 = value;
					this.SendPropertyChanged("CallLetter1");
					this.OnCallLetter1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallLetter2", DbType="NVarChar(MAX)")]
		public string CallLetter2
		{
			get
			{
				return this._CallLetter2;
			}
			set
			{
				if ((this._CallLetter2 != value))
				{
					this.OnCallLetter2Changing(value);
					this.SendPropertyChanging();
					this._CallLetter2 = value;
					this.SendPropertyChanged("CallLetter2");
					this.OnCallLetter2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallLetter3", DbType="NVarChar(MAX)")]
		public string CallLetter3
		{
			get
			{
				return this._CallLetter3;
			}
			set
			{
				if ((this._CallLetter3 != value))
				{
					this.OnCallLetter3Changing(value);
					this.SendPropertyChanging();
					this._CallLetter3 = value;
					this.SendPropertyChanged("CallLetter3");
					this.OnCallLetter3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallLetter4", DbType="NVarChar(MAX)")]
		public string CallLetter4
		{
			get
			{
				return this._CallLetter4;
			}
			set
			{
				if ((this._CallLetter4 != value))
				{
					this.OnCallLetter4Changing(value);
					this.SendPropertyChanging();
					this._CallLetter4 = value;
					this.SendPropertyChanged("CallLetter4");
					this.OnCallLetter4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallLetter5", DbType="NVarChar(MAX)")]
		public string CallLetter5
		{
			get
			{
				return this._CallLetter5;
			}
			set
			{
				if ((this._CallLetter5 != value))
				{
					this.OnCallLetter5Changing(value);
					this.SendPropertyChanging();
					this._CallLetter5 = value;
					this.SendPropertyChanged("CallLetter5");
					this.OnCallLetter5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(50)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VendorDetail")]
	public partial class VendorDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private string _VendorType;
		
		private string _CompanyName;
		
		private string _OfficeAddress;
		
		private string _FactoryAddress;
		
		private string _ContactPerson;
		
		private string _PhoneNo;
		
		private string _MobileNo;
		
		private string _Email;
		
		private string _Website;
		
		private string _Designation;
		
		private string _BusinessType;
		
		private string _Sector;
		
		private string _Expert;
		
		private System.Nullable<int> _EstablishedYear;
		
		private System.Nullable<int> _NoOfEmployees;
		
		private string _AnnualTurnover;
		
		private string _Source;
		
		private string _Note;
		
		private System.DateTime _ProcessedDate;
		
		private string _Profile1;
		
		private string _Profile2;
		
		private bool _Networking;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnVendorTypeChanging(string value);
    partial void OnVendorTypeChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnOfficeAddressChanging(string value);
    partial void OnOfficeAddressChanged();
    partial void OnFactoryAddressChanging(string value);
    partial void OnFactoryAddressChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnSectorChanging(string value);
    partial void OnSectorChanged();
    partial void OnExpertChanging(string value);
    partial void OnExpertChanged();
    partial void OnEstablishedYearChanging(System.Nullable<int> value);
    partial void OnEstablishedYearChanged();
    partial void OnNoOfEmployeesChanging(System.Nullable<int> value);
    partial void OnNoOfEmployeesChanged();
    partial void OnAnnualTurnoverChanging(string value);
    partial void OnAnnualTurnoverChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnProcessedDateChanging(System.DateTime value);
    partial void OnProcessedDateChanged();
    partial void OnProfile1Changing(string value);
    partial void OnProfile1Changed();
    partial void OnProfile2Changing(string value);
    partial void OnProfile2Changed();
    partial void OnNetworkingChanging(bool value);
    partial void OnNetworkingChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public VendorDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VendorType
		{
			get
			{
				return this._VendorType;
			}
			set
			{
				if ((this._VendorType != value))
				{
					this.OnVendorTypeChanging(value);
					this.SendPropertyChanging();
					this._VendorType = value;
					this.SendPropertyChanged("VendorType");
					this.OnVendorTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeAddress", DbType="NVarChar(250)")]
		public string OfficeAddress
		{
			get
			{
				return this._OfficeAddress;
			}
			set
			{
				if ((this._OfficeAddress != value))
				{
					this.OnOfficeAddressChanging(value);
					this.SendPropertyChanging();
					this._OfficeAddress = value;
					this.SendPropertyChanged("OfficeAddress");
					this.OnOfficeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryAddress", DbType="NVarChar(250)")]
		public string FactoryAddress
		{
			get
			{
				return this._FactoryAddress;
			}
			set
			{
				if ((this._FactoryAddress != value))
				{
					this.OnFactoryAddressChanging(value);
					this.SendPropertyChanging();
					this._FactoryAddress = value;
					this.SendPropertyChanged("FactoryAddress");
					this.OnFactoryAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="NVarChar(15)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this.OnPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PhoneNo = value;
					this.SendPropertyChanged("PhoneNo");
					this.OnPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expert", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Expert
		{
			get
			{
				return this._Expert;
			}
			set
			{
				if ((this._Expert != value))
				{
					this.OnExpertChanging(value);
					this.SendPropertyChanging();
					this._Expert = value;
					this.SendPropertyChanged("Expert");
					this.OnExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstablishedYear", DbType="Int")]
		public System.Nullable<int> EstablishedYear
		{
			get
			{
				return this._EstablishedYear;
			}
			set
			{
				if ((this._EstablishedYear != value))
				{
					this.OnEstablishedYearChanging(value);
					this.SendPropertyChanging();
					this._EstablishedYear = value;
					this.SendPropertyChanged("EstablishedYear");
					this.OnEstablishedYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfEmployees", DbType="Int")]
		public System.Nullable<int> NoOfEmployees
		{
			get
			{
				return this._NoOfEmployees;
			}
			set
			{
				if ((this._NoOfEmployees != value))
				{
					this.OnNoOfEmployeesChanging(value);
					this.SendPropertyChanging();
					this._NoOfEmployees = value;
					this.SendPropertyChanged("NoOfEmployees");
					this.OnNoOfEmployeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnualTurnover", DbType="NVarChar(50)")]
		public string AnnualTurnover
		{
			get
			{
				return this._AnnualTurnover;
			}
			set
			{
				if ((this._AnnualTurnover != value))
				{
					this.OnAnnualTurnoverChanging(value);
					this.SendPropertyChanging();
					this._AnnualTurnover = value;
					this.SendPropertyChanged("AnnualTurnover");
					this.OnAnnualTurnoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(250)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedDate", DbType="Date NOT NULL")]
		public System.DateTime ProcessedDate
		{
			get
			{
				return this._ProcessedDate;
			}
			set
			{
				if ((this._ProcessedDate != value))
				{
					this.OnProcessedDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessedDate = value;
					this.SendPropertyChanged("ProcessedDate");
					this.OnProcessedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile1", DbType="NVarChar(MAX)")]
		public string Profile1
		{
			get
			{
				return this._Profile1;
			}
			set
			{
				if ((this._Profile1 != value))
				{
					this.OnProfile1Changing(value);
					this.SendPropertyChanging();
					this._Profile1 = value;
					this.SendPropertyChanged("Profile1");
					this.OnProfile1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile2", DbType="NVarChar(MAX)")]
		public string Profile2
		{
			get
			{
				return this._Profile2;
			}
			set
			{
				if ((this._Profile2 != value))
				{
					this.OnProfile2Changing(value);
					this.SendPropertyChanging();
					this._Profile2 = value;
					this.SendPropertyChanged("Profile2");
					this.OnProfile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Networking", DbType="Bit NOT NULL")]
		public bool Networking
		{
			get
			{
				return this._Networking;
			}
			set
			{
				if ((this._Networking != value))
				{
					this.OnNetworkingChanging(value);
					this.SendPropertyChanging();
					this._Networking = value;
					this.SendPropertyChanged("Networking");
					this.OnNetworkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(50)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerDetail")]
	public partial class CustomerDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private string _CompanyType;
		
		private string _CompanyName;
		
		private string _OfficeAddress;
		
		private string _FactoryAddress;
		
		private string _ContactPerson;
		
		private string _PhoneNo;
		
		private string _MobileNo;
		
		private string _Email;
		
		private string _Website;
		
		private string _BusinessType;
		
		private string _Sector;
		
		private string _Expert;
		
		private System.Nullable<int> _EstablishedYear;
		
		private System.Nullable<int> _NoOfEmployees;
		
		private string _AnnualTurnover;
		
		private string _Source;
		
		private string _Note;
		
		private System.DateTime _ProcessedDate;
		
		private string _Profile1;
		
		private string _Profile2;
		
		private bool _Networking;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnCompanyTypeChanging(string value);
    partial void OnCompanyTypeChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnOfficeAddressChanging(string value);
    partial void OnOfficeAddressChanged();
    partial void OnFactoryAddressChanging(string value);
    partial void OnFactoryAddressChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnSectorChanging(string value);
    partial void OnSectorChanged();
    partial void OnExpertChanging(string value);
    partial void OnExpertChanged();
    partial void OnEstablishedYearChanging(System.Nullable<int> value);
    partial void OnEstablishedYearChanged();
    partial void OnNoOfEmployeesChanging(System.Nullable<int> value);
    partial void OnNoOfEmployeesChanged();
    partial void OnAnnualTurnoverChanging(string value);
    partial void OnAnnualTurnoverChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnProcessedDateChanging(System.DateTime value);
    partial void OnProcessedDateChanged();
    partial void OnProfile1Changing(string value);
    partial void OnProfile1Changed();
    partial void OnProfile2Changing(string value);
    partial void OnProfile2Changed();
    partial void OnNetworkingChanging(bool value);
    partial void OnNetworkingChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public CustomerDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CompanyType
		{
			get
			{
				return this._CompanyType;
			}
			set
			{
				if ((this._CompanyType != value))
				{
					this.OnCompanyTypeChanging(value);
					this.SendPropertyChanging();
					this._CompanyType = value;
					this.SendPropertyChanged("CompanyType");
					this.OnCompanyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeAddress", DbType="NVarChar(250)")]
		public string OfficeAddress
		{
			get
			{
				return this._OfficeAddress;
			}
			set
			{
				if ((this._OfficeAddress != value))
				{
					this.OnOfficeAddressChanging(value);
					this.SendPropertyChanging();
					this._OfficeAddress = value;
					this.SendPropertyChanged("OfficeAddress");
					this.OnOfficeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryAddress", DbType="NVarChar(250)")]
		public string FactoryAddress
		{
			get
			{
				return this._FactoryAddress;
			}
			set
			{
				if ((this._FactoryAddress != value))
				{
					this.OnFactoryAddressChanging(value);
					this.SendPropertyChanging();
					this._FactoryAddress = value;
					this.SendPropertyChanged("FactoryAddress");
					this.OnFactoryAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="NVarChar(15)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this.OnPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PhoneNo = value;
					this.SendPropertyChanged("PhoneNo");
					this.OnPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expert", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Expert
		{
			get
			{
				return this._Expert;
			}
			set
			{
				if ((this._Expert != value))
				{
					this.OnExpertChanging(value);
					this.SendPropertyChanging();
					this._Expert = value;
					this.SendPropertyChanged("Expert");
					this.OnExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstablishedYear", DbType="Int")]
		public System.Nullable<int> EstablishedYear
		{
			get
			{
				return this._EstablishedYear;
			}
			set
			{
				if ((this._EstablishedYear != value))
				{
					this.OnEstablishedYearChanging(value);
					this.SendPropertyChanging();
					this._EstablishedYear = value;
					this.SendPropertyChanged("EstablishedYear");
					this.OnEstablishedYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfEmployees", DbType="Int")]
		public System.Nullable<int> NoOfEmployees
		{
			get
			{
				return this._NoOfEmployees;
			}
			set
			{
				if ((this._NoOfEmployees != value))
				{
					this.OnNoOfEmployeesChanging(value);
					this.SendPropertyChanging();
					this._NoOfEmployees = value;
					this.SendPropertyChanged("NoOfEmployees");
					this.OnNoOfEmployeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnualTurnover", DbType="NVarChar(50)")]
		public string AnnualTurnover
		{
			get
			{
				return this._AnnualTurnover;
			}
			set
			{
				if ((this._AnnualTurnover != value))
				{
					this.OnAnnualTurnoverChanging(value);
					this.SendPropertyChanging();
					this._AnnualTurnover = value;
					this.SendPropertyChanged("AnnualTurnover");
					this.OnAnnualTurnoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(250)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedDate", DbType="Date NOT NULL")]
		public System.DateTime ProcessedDate
		{
			get
			{
				return this._ProcessedDate;
			}
			set
			{
				if ((this._ProcessedDate != value))
				{
					this.OnProcessedDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessedDate = value;
					this.SendPropertyChanged("ProcessedDate");
					this.OnProcessedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile1", DbType="NVarChar(MAX)")]
		public string Profile1
		{
			get
			{
				return this._Profile1;
			}
			set
			{
				if ((this._Profile1 != value))
				{
					this.OnProfile1Changing(value);
					this.SendPropertyChanging();
					this._Profile1 = value;
					this.SendPropertyChanged("Profile1");
					this.OnProfile1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile2", DbType="NVarChar(MAX)")]
		public string Profile2
		{
			get
			{
				return this._Profile2;
			}
			set
			{
				if ((this._Profile2 != value))
				{
					this.OnProfile2Changing(value);
					this.SendPropertyChanging();
					this._Profile2 = value;
					this.SendPropertyChanged("Profile2");
					this.OnProfile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Networking", DbType="Bit NOT NULL")]
		public bool Networking
		{
			get
			{
				return this._Networking;
			}
			set
			{
				if ((this._Networking != value))
				{
					this.OnNetworkingChanging(value);
					this.SendPropertyChanging();
					this._Networking = value;
					this.SendPropertyChanged("Networking");
					this.OnNetworkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(50)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMSHistory")]
	public partial class SMSHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private System.DateTime _Date;
		
		private string _MobileNo;
		
		private string _SMSText;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnSMSTextChanging(string value);
    partial void OnSMSTextChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public SMSHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSText", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string SMSText
		{
			get
			{
				return this._SMSText;
			}
			set
			{
				if ((this._SMSText != value))
				{
					this.OnSMSTextChanging(value);
					this.SendPropertyChanging();
					this._SMSText = value;
					this.SendPropertyChanged("SMSText");
					this.OnSMSTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(MAX)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VisitDetail")]
	public partial class VisitDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private string _CompanyName;
		
		private string _ContactPerson;
		
		private string _VisitType;
		
		private System.DateTime _VisitDate;
		
		private string _VisitTime;
		
		private string _CommentRemark;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnVisitTypeChanging(string value);
    partial void OnVisitTypeChanged();
    partial void OnVisitDateChanging(System.DateTime value);
    partial void OnVisitDateChanged();
    partial void OnVisitTimeChanging(string value);
    partial void OnVisitTimeChanged();
    partial void OnCommentRemarkChanging(string value);
    partial void OnCommentRemarkChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public VisitDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(100)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VisitType
		{
			get
			{
				return this._VisitType;
			}
			set
			{
				if ((this._VisitType != value))
				{
					this.OnVisitTypeChanging(value);
					this.SendPropertyChanging();
					this._VisitType = value;
					this.SendPropertyChanged("VisitType");
					this.OnVisitTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitDate", DbType="Date NOT NULL")]
		public System.DateTime VisitDate
		{
			get
			{
				return this._VisitDate;
			}
			set
			{
				if ((this._VisitDate != value))
				{
					this.OnVisitDateChanging(value);
					this.SendPropertyChanging();
					this._VisitDate = value;
					this.SendPropertyChanged("VisitDate");
					this.OnVisitDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VisitTime
		{
			get
			{
				return this._VisitTime;
			}
			set
			{
				if ((this._VisitTime != value))
				{
					this.OnVisitTimeChanging(value);
					this.SendPropertyChanging();
					this._VisitTime = value;
					this.SendPropertyChanged("VisitTime");
					this.OnVisitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentRemark", DbType="NVarChar(MAX)")]
		public string CommentRemark
		{
			get
			{
				return this._CommentRemark;
			}
			set
			{
				if ((this._CommentRemark != value))
				{
					this.OnCommentRemarkChanging(value);
					this.SendPropertyChanging();
					this._CommentRemark = value;
					this.SendPropertyChanged("CommentRemark");
					this.OnCommentRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(50)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailHistory")]
	public partial class EmailHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SrNo;
		
		private System.DateTime _Date;
		
		private string _EmailIds;
		
		private string _Subject;
		
		private string _Message;
		
		private string _ExecutiveName;
		
		private System.Nullable<System.DateTime> _ModifiedDateTime;
		
		private bool _IsDeleted;
		
		private string _DeletedReason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrNoChanging(long value);
    partial void OnSrNoChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnEmailIdsChanging(string value);
    partial void OnEmailIdsChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnExecutiveNameChanging(string value);
    partial void OnExecutiveNameChanged();
    partial void OnModifiedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateTimeChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    #endregion
		
		public EmailHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailIds", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string EmailIds
		{
			get
			{
				return this._EmailIds;
			}
			set
			{
				if ((this._EmailIds != value))
				{
					this.OnEmailIdsChanging(value);
					this.SendPropertyChanging();
					this._EmailIds = value;
					this.SendPropertyChanged("EmailIds");
					this.OnEmailIdsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExecutiveName
		{
			get
			{
				return this._ExecutiveName;
			}
			set
			{
				if ((this._ExecutiveName != value))
				{
					this.OnExecutiveNameChanging(value);
					this.SendPropertyChanging();
					this._ExecutiveName = value;
					this.SendPropertyChanged("ExecutiveName");
					this.OnExecutiveNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDateTime
		{
			get
			{
				return this._ModifiedDateTime;
			}
			set
			{
				if ((this._ModifiedDateTime != value))
				{
					this.OnModifiedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDateTime = value;
					this.SendPropertyChanged("ModifiedDateTime");
					this.OnModifiedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="NVarChar(MAX)")]
		public string DeletedReason
		{
			get
			{
				return this._DeletedReason;
			}
			set
			{
				if ((this._DeletedReason != value))
				{
					this.OnDeletedReasonChanging(value);
					this.SendPropertyChanging();
					this._DeletedReason = value;
					this.SendPropertyChanged("DeletedReason");
					this.OnDeletedReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
