//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIFreelancerDataBaseEntry.CCandidateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidateDetail", Namespace="http://schemas.datacontract.org/2004/07/UniWcfService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailSearchRequest))]
    public partial class CandidateDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalQualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CandidateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentCTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentIndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutiveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpSlapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedCTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandLineNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferedLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredIndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProcessedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SrNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalQualification {
            get {
                return this.AdditionalQualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalQualificationField, value) != true)) {
                    this.AdditionalQualificationField = value;
                    this.RaisePropertyChanged("AdditionalQualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVPath {
            get {
                return this.CVPathField;
            }
            set {
                if ((object.ReferenceEquals(this.CVPathField, value) != true)) {
                    this.CVPathField = value;
                    this.RaisePropertyChanged("CVPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CandidateCode {
            get {
                return this.CandidateCodeField;
            }
            set {
                if ((this.CandidateCodeField.Equals(value) != true)) {
                    this.CandidateCodeField = value;
                    this.RaisePropertyChanged("CandidateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentCTC {
            get {
                return this.CurrentCTCField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentCTCField, value) != true)) {
                    this.CurrentCTCField = value;
                    this.RaisePropertyChanged("CurrentCTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentIndustry {
            get {
                return this.CurrentIndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentIndustryField, value) != true)) {
                    this.CurrentIndustryField = value;
                    this.RaisePropertyChanged("CurrentIndustry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentLocationField, value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedReason {
            get {
                return this.DeletedReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedReasonField, value) != true)) {
                    this.DeletedReasonField = value;
                    this.RaisePropertyChanged("DeletedReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutiveName {
            get {
                return this.ExecutiveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutiveNameField, value) != true)) {
                    this.ExecutiveNameField = value;
                    this.RaisePropertyChanged("ExecutiveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpSlap {
            get {
                return this.ExpSlapField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpSlapField, value) != true)) {
                    this.ExpSlapField = value;
                    this.RaisePropertyChanged("ExpSlap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedCTC {
            get {
                return this.ExpectedCTCField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedCTCField, value) != true)) {
                    this.ExpectedCTCField = value;
                    this.RaisePropertyChanged("ExpectedCTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LandLineNo {
            get {
                return this.LandLineNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LandLineNoField, value) != true)) {
                    this.LandLineNoField = value;
                    this.RaisePropertyChanged("LandLineNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarritalStatus {
            get {
                return this.MarritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MarritalStatusField, value) != true)) {
                    this.MarritalStatusField = value;
                    this.RaisePropertyChanged("MarritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDateTime {
            get {
                return this.ModifiedDateTimeField;
            }
            set {
                if ((this.ModifiedDateTimeField.Equals(value) != true)) {
                    this.ModifiedDateTimeField = value;
                    this.RaisePropertyChanged("ModifiedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfCalls {
            get {
                return this.NoOfCallsField;
            }
            set {
                if ((this.NoOfCallsField.Equals(value) != true)) {
                    this.NoOfCallsField = value;
                    this.RaisePropertyChanged("NoOfCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoticePeriod {
            get {
                return this.NoticePeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticePeriodField, value) != true)) {
                    this.NoticePeriodField = value;
                    this.RaisePropertyChanged("NoticePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferedLocation {
            get {
                return this.PreferedLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferedLocationField, value) != true)) {
                    this.PreferedLocationField = value;
                    this.RaisePropertyChanged("PreferedLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredIndustry {
            get {
                return this.PreferredIndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredIndustryField, value) != true)) {
                    this.PreferredIndustryField = value;
                    this.RaisePropertyChanged("PreferredIndustry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProcessedDate {
            get {
                return this.ProcessedDateField;
            }
            set {
                if ((this.ProcessedDateField.Equals(value) != true)) {
                    this.ProcessedDateField = value;
                    this.RaisePropertyChanged("ProcessedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualification {
            get {
                return this.QualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationField, value) != true)) {
                    this.QualificationField = value;
                    this.RaisePropertyChanged("Qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SrNo {
            get {
                return this.SrNoField;
            }
            set {
                if ((this.SrNoField.Equals(value) != true)) {
                    this.SrNoField = value;
                    this.RaisePropertyChanged("SrNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidateDetailSearchRequest", Namespace="http://schemas.datacontract.org/2004/07/UniWcfService.Candidate")]
    [System.SerializableAttribute()]
    public partial class CandidateDetailSearchRequest : UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetail {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] AgeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] ExpMonthListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromProcessedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchByProcessedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToProcessedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] AgeList {
            get {
                return this.AgeListField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeListField, value) != true)) {
                    this.AgeListField = value;
                    this.RaisePropertyChanged("AgeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] ExpMonthList {
            get {
                return this.ExpMonthListField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpMonthListField, value) != true)) {
                    this.ExpMonthListField = value;
                    this.RaisePropertyChanged("ExpMonthList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromProcessedDate {
            get {
                return this.FromProcessedDateField;
            }
            set {
                if ((this.FromProcessedDateField.Equals(value) != true)) {
                    this.FromProcessedDateField = value;
                    this.RaisePropertyChanged("FromProcessedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNo {
            get {
                return this.PageNoField;
            }
            set {
                if ((this.PageNoField.Equals(value) != true)) {
                    this.PageNoField = value;
                    this.RaisePropertyChanged("PageNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchByProcessedDate {
            get {
                return this.SearchByProcessedDateField;
            }
            set {
                if ((this.SearchByProcessedDateField.Equals(value) != true)) {
                    this.SearchByProcessedDateField = value;
                    this.RaisePropertyChanged("SearchByProcessedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToProcessedDate {
            get {
                return this.ToProcessedDateField;
            }
            set {
                if ((this.ToProcessedDateField.Equals(value) != true)) {
                    this.ToProcessedDateField = value;
                    this.RaisePropertyChanged("ToProcessedDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidateDetailResponse", Namespace="http://schemas.datacontract.org/2004/07/UniWcfService")]
    [System.SerializableAttribute()]
    public partial class CandidateDetailResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailDto[] PageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailDto[] PageData {
            get {
                return this.PageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PageDataField, value) != true)) {
                    this.PageDataField = value;
                    this.RaisePropertyChanged("PageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalItem {
            get {
                return this.TotalItemField;
            }
            set {
                if ((this.TotalItemField.Equals(value) != true)) {
                    this.TotalItemField = value;
                    this.RaisePropertyChanged("TotalItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidateDetailDto", Namespace="http://schemas.datacontract.org/2004/07/UniWcfService.Candidate")]
    [System.SerializableAttribute()]
    public partial class CandidateDetailDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SrNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProcessedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CandidateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferedLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandLineNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalQualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpSlapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentIndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredIndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentCTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedCTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SrNo {
            get {
                return this.SrNoField;
            }
            set {
                if ((this.SrNoField.Equals(value) != true)) {
                    this.SrNoField = value;
                    this.RaisePropertyChanged("SrNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime ProcessedDate {
            get {
                return this.ProcessedDateField;
            }
            set {
                if ((this.ProcessedDateField.Equals(value) != true)) {
                    this.ProcessedDateField = value;
                    this.RaisePropertyChanged("ProcessedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<long> CandidateCode {
            get {
                return this.CandidateCodeField;
            }
            set {
                if ((this.CandidateCodeField.Equals(value) != true)) {
                    this.CandidateCodeField = value;
                    this.RaisePropertyChanged("CandidateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string MarritalStatus {
            get {
                return this.MarritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MarritalStatusField, value) != true)) {
                    this.MarritalStatusField = value;
                    this.RaisePropertyChanged("MarritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentLocationField, value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PreferedLocation {
            get {
                return this.PreferedLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferedLocationField, value) != true)) {
                    this.PreferedLocationField = value;
                    this.RaisePropertyChanged("PreferedLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string LandLineNo {
            get {
                return this.LandLineNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LandLineNoField, value) != true)) {
                    this.LandLineNoField = value;
                    this.RaisePropertyChanged("LandLineNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Qualification {
            get {
                return this.QualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationField, value) != true)) {
                    this.QualificationField = value;
                    this.RaisePropertyChanged("Qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string AdditionalQualification {
            get {
                return this.AdditionalQualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalQualificationField, value) != true)) {
                    this.AdditionalQualificationField = value;
                    this.RaisePropertyChanged("AdditionalQualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ExpSlap {
            get {
                return this.ExpSlapField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpSlapField, value) != true)) {
                    this.ExpSlapField = value;
                    this.RaisePropertyChanged("ExpSlap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string CurrentIndustry {
            get {
                return this.CurrentIndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentIndustryField, value) != true)) {
                    this.CurrentIndustryField = value;
                    this.RaisePropertyChanged("CurrentIndustry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string PreferredIndustry {
            get {
                return this.PreferredIndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredIndustryField, value) != true)) {
                    this.PreferredIndustryField = value;
                    this.RaisePropertyChanged("PreferredIndustry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string NoticePeriod {
            get {
                return this.NoticePeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticePeriodField, value) != true)) {
                    this.NoticePeriodField = value;
                    this.RaisePropertyChanged("NoticePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string CurrentCTC {
            get {
                return this.CurrentCTCField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentCTCField, value) != true)) {
                    this.CurrentCTCField = value;
                    this.RaisePropertyChanged("CurrentCTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string ExpectedCTC {
            get {
                return this.ExpectedCTCField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedCTCField, value) != true)) {
                    this.ExpectedCTCField = value;
                    this.RaisePropertyChanged("ExpectedCTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCandidateService.ICandidateService")]
    public interface ICandidateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandidateService/GetCandidate", ReplyAction="http://tempuri.org/ICandidateService/GetCandidateResponse")]
        UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetail GetCandidate(long srNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandidateService/GetCandidate", ReplyAction="http://tempuri.org/ICandidateService/GetCandidateResponse")]
        System.Threading.Tasks.Task<UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetail> GetCandidateAsync(long srNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandidateService/GetCandidates", ReplyAction="http://tempuri.org/ICandidateService/GetCandidatesResponse")]
        UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailResponse GetCandidates(UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailSearchRequest candidate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandidateService/GetCandidates", ReplyAction="http://tempuri.org/ICandidateService/GetCandidatesResponse")]
        System.Threading.Tasks.Task<UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailResponse> GetCandidatesAsync(UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailSearchRequest candidate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICandidateServiceChannel : UNIFreelancerDataBaseEntry.CCandidateService.ICandidateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CandidateServiceClient : System.ServiceModel.ClientBase<UNIFreelancerDataBaseEntry.CCandidateService.ICandidateService>, UNIFreelancerDataBaseEntry.CCandidateService.ICandidateService {
        
        public CandidateServiceClient() {
        }
        
        public CandidateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CandidateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetail GetCandidate(long srNo) {
            return base.Channel.GetCandidate(srNo);
        }
        
        public System.Threading.Tasks.Task<UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetail> GetCandidateAsync(long srNo) {
            return base.Channel.GetCandidateAsync(srNo);
        }
        
        public UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailResponse GetCandidates(UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailSearchRequest candidate) {
            return base.Channel.GetCandidates(candidate);
        }
        
        public System.Threading.Tasks.Task<UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailResponse> GetCandidatesAsync(UNIFreelancerDataBaseEntry.CCandidateService.CandidateDetailSearchRequest candidate) {
            return base.Channel.GetCandidatesAsync(candidate);
        }
    }
}
